# Imagen base con Python 3.11
FROM python:3.11-slim

# Evitar archivos pyc y asegurar logs inmediatos
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Crear carpeta de trabajo
WORKDIR /app

# Instalar herramientas básicas del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libz-dev \
    libbz2-dev \
    liblzma-dev \
    libglpk-dev \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements.txt al contenedor
COPY requirements.txt .

# Instalar paquetes de Python
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
